project:
  type: website
  output-dir: docs

website:
  title: "fate.threads"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: posts/
        text: Posts

format:
  html:
    theme:
      - darkly
      - brand
    css: styles.css
    toc: true



